apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-data-volume
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadOnlyMany 
  hostPath:
    path: /run/desktop/mnt/host/c/logs
    type: Directory