apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data-volume-claim
spec:
  volumeName: log-data-volume
  accessModes:
    - ReadOnlyMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi